(()=>{
'use strict';
const APP='auditarEpiV1',STOCK='auditarEpiStockV1',REC='gestaoEpiRecentWorkersV300';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(k,f)=>{try{return {...f,...JSON.parse(localStorage.getItem(k)||'{}')}}catch{return f}};
const data=()=>read(APP,{companies:[],workers:[],epis:[],deliveries:[]});
const stock=()=>read(STOCK,{movements:[]});
function toast(m){const e=$('#toast');if(!e)return alert(m);e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function go(id){document.querySelector('[data-go="'+id+'"]')?.click()}
function field(note,key){const p=String(note||'').split('|').map(x=>x.trim()).find(x=>x.toLowerCase().startsWith(key.toLowerCase()+':'));return p?p.slice(p.indexOf(':')+1).trim():''}
function returned(st,wid,eid){return (st.movements||[]).filter(m=>String(m?.note||'').startsWith('DEVOLUÇÃO EPI')&&m.epiId===eid&&field(m.note,'workerId')===wid).reduce((s,m)=>s+Number(field(m.note,'qtd')||0),0)}
function held(a,st,wid,eid){const d=(a.deliveries||[]).filter(x=>x.workerId===wid&&x.cancelled!==true).reduce((s,x)=>s+(x.items||[]).filter(i=>i.epiId===eid).reduce((q,i)=>q+Number(i.qty||0),0),0);return Math.max(0,d-returned(st,wid,eid))}
function style(){if($('#ux300Style'))return;const s=document.createElement('style');s.id='ux300Style';s.textContent=`
.ux300-status{display:flex;justify-content:space-between;gap:8px;background:#fff;border:1px solid var(--line);border-radius:13px;padding:9px 11px;margin-bottom:10px;font-size:10px;color:#607975}.ux300-status b{color:#28544e}.ux300-dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:5px}.ux300-dot.on{background:#0ba87e}.ux300-dot.off{background:#d97706}
.ux300-search{position:relative;margin-bottom:10px}.ux300-search input{padding-left:40px!important}.ux300-search:before{content:'⌕';position:absolute;left:14px;top:7px;font-size:24px;color:#68817d}.ux300-results{display:none;position:absolute;z-index:90;left:0;right:0;top:54px;background:#fff;border:1px solid #d8e7e4;border-radius:14px;box-shadow:0 18px 45px rgba(17,61,56,.18);max-height:300px;overflow:auto}.ux300-results.open{display:block}.ux300-result{width:100%;border:0;border-top:1px solid #edf2f1;background:#fff;text-align:left;padding:11px;color:#173d39}.ux300-result small{display:block;color:#718682;font-size:9px}
.ux300-quick{display:grid;grid-template-columns:1.3fr 1fr;gap:9px;margin:10px 0}.ux300-q{border:1px solid #d6e5e2;background:#fff;border-radius:16px;padding:13px;text-align:left;color:#173d39;min-height:78px}.ux300-q.primary{background:linear-gradient(135deg,#0aa47c,#06695a);color:#fff;border:0}.ux300-q span{display:block;font-size:22px}.ux300-q b{display:block;margin-top:4px}.ux300-q small{font-size:9px;opacity:.78}
.ux300-recent{margin:10px 0}.ux300-recent h3{font-size:12px;margin:0 0 6px}.ux300-recent-row{display:flex;gap:7px;overflow:auto}.ux300-recent button{flex:0 0 auto;border:1px solid #d8e7e4;background:#fff;border-radius:11px;padding:8px 10px;text-align:left;max-width:180px}.ux300-recent b,.ux300-recent small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ux300-recent small{font-size:9px;color:#718682}
.ux300-more summary{cursor:pointer;text-align:center;padding:10px;color:#0f766e;font-weight:900;font-size:12px}
.ux300-modal{position:fixed;inset:0;z-index:25000;background:rgba(5,34,31,.75);display:none;align-items:flex-end;justify-content:center}.ux300-modal.open{display:flex}.ux300-sheet{width:min(680px,100%);max-height:92vh;overflow:auto;background:#f8fbfa;border-radius:24px 24px 0 0;padding:17px}.ux300-head{display:flex;justify-content:space-between;gap:10px}.ux300-head h2{margin:0;font-size:19px}.ux300-head p{margin:3px 0;color:#718682;font-size:10px}.ux300-close{width:40px;height:40px;border:0;border-radius:12px;background:#e9f3f1;font-size:22px}.ux300-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:10px 0}.ux300-kpi{background:#fff;border:1px solid #dce8e5;border-radius:13px;padding:9px;text-align:center}.ux300-kpi strong{display:block;font-size:18px}.ux300-kpi span{font-size:9px;color:#718682}.ux300-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:10px 0}.ux300-action{border:0;border-radius:13px;padding:11px 8px;font-weight:900;background:#eaf6f3;color:#0b6e5d}.ux300-action.primary{background:#0f766e;color:#fff}.ux300-held{display:grid;gap:7px}.ux300-held-row{background:#fff;border:1px solid #dce8e5;border-radius:12px;padding:10px}.ux300-held-row small{display:block;color:#718682;font-size:9px;margin-top:3px}
.ux300-success{position:fixed;inset:0;z-index:26000;background:rgba(5,34,31,.72);display:none;align-items:center;justify-content:center;padding:18px}.ux300-success.open{display:flex}.ux300-success-card{width:min(390px,100%);background:#fff;border-radius:22px;padding:22px;text-align:center}.ux300-success-icon{width:64px;height:64px;border-radius:50%;display:grid;place-items:center;margin:0 auto 10px;background:#e8f8f1;color:#08815f;font-size:32px;font-weight:900}.ux300-success-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:13px}.ux300-success-actions button{border:0;border-radius:12px;padding:11px;font-weight:900}.ux300-success-actions .primary{background:#0f766e;color:#fff}
@media(min-width:700px){.ux300-quick{grid-template-columns:repeat(4,1fr)}.ux300-modal{align-items:center;padding:22px}.ux300-sheet{border-radius:24px}}
`;document.head.appendChild(s)}
function recent(){try{return JSON.parse(localStorage.getItem(REC)||'[]')}catch{return[]}}
function remember(id){localStorage.setItem(REC,JSON.stringify([id,...recent().filter(x=>x!==id)].slice(0,6)));renderRecent()}
function renderRecent(){const box=$('#ux300Recent');if(!box)return;const a=data(),rows=recent().map(id=>a.workers.find(w=>w.id===id)).filter(Boolean);box.innerHTML=rows.length?'<h3>Recentes</h3><div class="ux300-recent-row">'+rows.map(w=>`<button data-ux-worker="${esc(w.id)}"><b>${esc(w.name)}</b><small>${esc(w.role||w.sector||'Trabalhador')}</small></button>`).join('')+'</div>':''}
function injectHome(){const home=$('#home');if(!home||$('#ux300Quick'))return;const hero=home.querySelector('.hero-card');const status=document.createElement('div');status.id='ux300Status';status.className='ux300-status';status.innerHTML='<span><i class="ux300-dot"></i><b>Conexão</b></span><span id="ux300Sync">—</span>';hero?.before(status);const search=document.createElement('div');search.className='ux300-search';search.innerHTML='<input id="ux300Search" placeholder="Buscar trabalhador, EPI, CA ou matrícula"><div id="ux300Results" class="ux300-results"></div>';status.after(search);const q=document.createElement('div');q.id='ux300Quick';q.className='ux300-quick';q.innerHTML='<button class="ux300-q primary" data-go="delivery"><span>＋</span><b>Nova entrega</b><small>fluxo rápido</small></button><button class="ux300-q" id="ux300Qr"><span>▣</span><b>Ler QR</b><small>identificar trabalhador</small></button><button class="ux300-q" data-go="epiReturn"><span>↩</span><b>Trocar / devolver</b><small>menos etapas</small></button><button class="ux300-q" data-go="workers"><span>👷</span><b>Trabalhadores</b><small>ficha 360°</small></button>';search.after(q);const r=document.createElement('div');r.id='ux300Recent';r.className='ux300-recent';q.after(r);renderRecent();const grid=home.querySelector('.menu-grid');if(grid&&!grid.closest('.ux300-more')){const d=document.createElement('details');d.className='ux300-more';d.innerHTML='<summary>Mais funções</summary>';grid.before(d);d.appendChild(grid)}$('#ux300Search')?.addEventListener('input',searchAll);$('#ux300Qr')?.addEventListener('click',qrPrompt)}
function updateStatus(){const el=$('#ux300Status');if(!el)return;const on=navigator.onLine;el.querySelector('.ux300-dot').className='ux300-dot '+(on?'on':'off');el.querySelector('b').textContent=on?'Online':'Offline • dados salvos no aparelho';$('#ux300Sync').textContent=$('#epiCloudStatus')?.textContent||'Aguardando'}
function searchAll(){const q=norm($('#ux300Search')?.value),box=$('#ux300Results');if(!box)return;if(q.length<2){box.classList.remove('open');return}const a=data(),out=[];a.workers.filter(w=>[w.name,w.cpf,w.reg,w.role,w.sector].some(v=>norm(v).includes(q))).slice(0,6).forEach(w=>out.push({t:'worker',id:w.id,n:w.name,s:[w.reg,w.role,w.sector].filter(Boolean).join(' • ')}));a.epis.filter(e=>[e.name,e.ca,e.model,e.size].some(v=>norm(v).includes(q))).slice(0,4).forEach(e=>out.push({t:'epi',id:e.id,n:e.name,s:e.ca?'CA '+e.ca:''}));box.innerHTML=out.length?out.map(x=>`<button class="ux300-result" data-ux-type="${x.t}" data-ux-id="${esc(x.id)}"><b>${esc(x.n)}</b><small>${esc(x.s)}</small></button>`).join(''):'<div style="padding:11px;color:#718682;font-size:10px">Nenhum resultado.</div>';box.classList.add('open')}
function decorateRows(){const list=$('#workerList');if(!list)return;list.querySelectorAll('.list-item').forEach(row=>{const d=row.querySelector('[data-del-worker]'),id=d?.dataset.delWorker;if(!id||row.querySelector('[data-ux-worker]'))return;const b=document.createElement('button');b.type='button';b.className='tiny';b.dataset.uxWorker=id;b.textContent='Abrir';row.querySelector('.list-actions')?.prepend(b)})}
function modal(){if($('#ux300Modal'))return;const d=document.createElement('div');d.id='ux300Modal';d.className='ux300-modal';d.innerHTML='<div class="ux300-sheet"><div class="ux300-head"><div><h2 id="ux300Name">Trabalhador</h2><p id="ux300Meta"></p></div><button class="ux300-close">×</button></div><div class="ux300-kpis"><div class="ux300-kpi"><strong id="ux300Held">0</strong><span>unidades em posse</span></div><div class="ux300-kpi"><strong id="ux300Del">0</strong><span>entregas</span></div><div class="ux300-kpi"><strong id="ux300Due">0</strong><span>trocas próximas</span></div></div><div class="ux300-actions"><button class="ux300-action primary" id="ux300Deliver">＋ Entregar</button><button class="ux300-action" id="ux300Replace">🔄 Trocar</button><button class="ux300-action" id="ux300Return">↩ Devolver</button><button class="ux300-action" id="ux300Kit">🧰 Kit sugerido</button></div><div id="ux300HeldList" class="ux300-held"></div></div>';document.body.appendChild(d);d.querySelector('.ux300-close').onclick=()=>d.classList.remove('open');d.addEventListener('click',e=>{if(e.target===d)d.classList.remove('open')})}
function suggestKit(a,w){const role=norm(w.role);if(!role)return[];const peers=new Set(a.workers.filter(x=>norm(x.role)===role).map(x=>x.id)),m=new Map();(a.deliveries||[]).filter(d=>peers.has(d.workerId)&&d.cancelled!==true).forEach(d=>(d.items||[]).forEach(i=>m.set(i.epiId,(m.get(i.epiId)||0)+Number(i.qty||1))));return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5).map(x=>x[0])}
function openWorker(id){modal();const a=data(),st=stock(),w=a.workers.find(x=>x.id===id);if(!w)return;remember(id);$('#ux300Name').textContent=w.name;$('#ux300Meta').textContent=[a.companies.find(c=>c.id===w.companyId)?.name,w.reg,w.role,w.sector].filter(Boolean).join(' • ');const heldRows=a.epis.map(e=>({e,qty:held(a,st,w.id,e.id)})).filter(x=>x.qty>0),del=(a.deliveries||[]).filter(d=>d.workerId===w.id&&d.cancelled!==true);$('#ux300Held').textContent=heldRows.reduce((s,x)=>s+x.qty,0);$('#ux300Del').textContent=del.length;let due=0;const html=heldRows.map(x=>{const last=del.filter(d=>(d.items||[]).some(i=>i.epiId===x.e.id)).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0];let t='';if(last&&Number(x.e.cycle||0)){const days=Math.ceil((new Date(last.createdAt).getTime()+Number(x.e.cycle)*86400000-Date.now())/86400000);if(days<=15)due++;t=days<0?' • troca vencida':' • troca em '+days+' dia(s)'}return `<div class="ux300-held-row"><b>${esc(x.e.name)} • Qtd. ${x.qty}</b><small>${x.e.ca?'CA '+esc(x.e.ca):'CA não informado'}${t}</small></div>`}).join('');$('#ux300Due').textContent=due;$('#ux300HeldList').innerHTML=html||'<div class="empty">Nenhum EPI em posse.</div>';const nav=(reason,kit)=>{$('#ux300Modal').classList.remove('open');go('delivery');setTimeout(()=>prefill(w,reason,kit),120)};$('#ux300Deliver').onclick=()=>nav('',[]);$('#ux300Replace').onclick=()=>nav('Substituição por desgaste',[]);$('#ux300Return').onclick=()=>{$('#ux300Modal').classList.remove('open');go('epiReturn');setTimeout(()=>{const c=$('#returnCompany');if(c){c.value=w.companyId;c.dispatchEvent(new Event('change',{bubbles:true}))}setTimeout(()=>{const s=$('#returnWorker');if(s){s.value=w.id;s.dispatchEvent(new Event('change',{bubbles:true}))}},100)},100)};$('#ux300Kit').onclick=()=>{const kit=suggestKit(a,w);if(!kit.length)return toast('Sem histórico suficiente para sugerir kit desta função.');nav('',kit)};$('#ux300Modal').classList.add('open')}
function prefill(w,reason,kit){const c=$('#deliveryCompany');if(c){c.value=w.companyId;c.dispatchEvent(new Event('change',{bubbles:true}))}setTimeout(()=>{const s=$('#deliveryWorker');if(s)s.value=w.id;if(reason){const r=$('#deliveryReason'),o=[...(r?.options||[])].find(x=>norm(x.value||x.textContent).includes(norm(reason)));if(o)r.value=o.value}if(kit?.length){while($$('#deliveryItems .delivery-item').length<kit.length)$('#btnAddItem')?.click();setTimeout(()=>$$('#deliveryItems .delivery-item').forEach((row,i)=>{if(kit[i])row.querySelector('.item-epi').value=kit[i]}),30)}},70)}
function qrPrompt(){const code=prompt('Leia o QR pelo leitor do aparelho ou informe CPF/matrícula/código do trabalhador:');if(!code)return;const q=norm(code).replace(/\D/g,''),a=data();const w=a.workers.find(x=>norm(x.id)===norm(code)||norm(x.reg)===norm(code)||String(x.cpf||'').replace(/\D/g,'')===q);if(!w)return toast('Trabalhador não encontrado.');openWorker(w.id)}
function success(){if($('#ux300Success'))return;const d=document.createElement('div');d.id='ux300Success';d.className='ux300-success';d.innerHTML='<div class="ux300-success-card"><div class="ux300-success-icon">✓</div><h2>Entrega registrada</h2><p>Registro salvo com sucesso.</p><div class="ux300-success-actions"><button id="ux300Next" class="primary">Próximo trabalhador</button><button id="ux300Receipt">Ver comprovante</button></div></div>';document.body.appendChild(d);$('#ux300Next').onclick=()=>{d.classList.remove('open');go('delivery')};$('#ux300Receipt').onclick=()=>d.classList.remove('open')}
function watchSuccess(){const b=$('#btnSaveDelivery');if(!b||b.dataset.ux300)return;b.dataset.ux300='1';b.addEventListener('click',()=>setTimeout(()=>{if($('#receipt')?.classList.contains('active'))$('#ux300Success')?.classList.add('open')},220))}
function boot(){style();success();injectHome();updateStatus();decorateRows();watchSuccess();setInterval(updateStatus,10000);let uxRaf=0;const o=new MutationObserver(()=>{if(uxRaf)return;uxRaf=requestAnimationFrame(()=>{uxRaf=0;injectHome();decorateRows();watchSuccess()})});o.observe(document.body,{childList:true,subtree:true});document.addEventListener('click',e=>{const w=e.target.closest('[data-ux-worker]');if(w){e.preventDefault();openWorker(w.dataset.uxWorker);return}const r=e.target.closest('[data-ux-type]');if(r){$('#ux300Results')?.classList.remove('open');if(r.dataset.uxType==='worker')openWorker(r.dataset.uxId);else if(r.dataset.uxType==='epi')go('epis')}});window.addEventListener('online',updateStatus);window.addEventListener('offline',updateStatus)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();