(() => {
  const ENDPOINT='https://script.google.com/macros/s/AKfycbxNG-wU-jZMKMR2cb1nR9OUd31GSUpGM0FIEagZEUP7sAHxkahLDuJ6T3wZvEe9rm6WrQ/exec';
  const BOOTSTRAP_KEY='__AUDITAR_SYNC_KEY__';
  const TOKEN_KEY='auditarSstMasterToken', USER_KEY='auditarSstMasterUser', DEVICE_KEY='auditarSstMasterDevice';
  let users=[],companies=[],currentUser=null,setupMode=false;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const token=()=>String(localStorage.getItem(TOKEN_KEY)||'').trim();
  const usernameOf=u=>String(u?.username||String(u?.email||'').split('@')[0]||'').trim();
  const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)};
  const cleanUsername=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9._-]+/g,'').replace(/^[._-]+|[._-]+$/g,'').slice(0,40);

  function deviceId(){let id=localStorage.getItem(DEVICE_KEY)||'';if(!id){id='master-'+(crypto?.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2));localStorage.setItem(DEVICE_KEY,id)}return id}
  async function api(action,extra={}){const body={action,...extra};if(token()&&!body.authToken)body.authToken=token();const c=new AbortController(),t=setTimeout(()=>c.abort(),28000);try{const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body),signal:c.signal});const x=await r.text();try{return JSON.parse(x)}catch(_){throw new Error('A Central Online retornou uma resposta inválida.')}}catch(e){if(e?.name==='AbortError')throw new Error('A Central Online demorou para responder. Tente novamente.');throw e}finally{clearTimeout(t)}}
  function clearSession(){localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(USER_KEY);currentUser=null}
  function saveSession(r){const tk=String(r.sessionToken||'').trim();if(!tk)throw new Error('A Central não retornou a sessão.');localStorage.setItem(TOKEN_KEY,tk);localStorage.setItem(USER_KEY,JSON.stringify(r.user||{}));currentUser=r.user||null;$('#adminDisplay').textContent=currentUser?.name||'Administrador'}

  function showLogin(message='',setup=false){setupMode=setup;$('#loginOverlay').classList.remove('hidden');$('#setupNameWrap').classList.toggle('hidden',!setup);$('#loginTitle').textContent=setup?'Criar administrador':'Painel Mestre';$('#loginText').textContent=setup?'Primeiro acesso: escolha seu usuário e sua senha de administrador.':'Acesso administrativo para controlar usuários do aplicativo de vistoria.';$('#btnLogin').textContent=setup?'Criar meu acesso':'Entrar';$('#loginError').textContent=message;setTimeout(()=>$(setup?'#setupName':'#loginUser')?.focus(),60)}
  const hideLogin=()=>$('#loginOverlay').classList.add('hidden');

  async function login(){
    const username=cleanUsername($('#loginUser').value),password=$('#loginPass').value,name=$('#setupName').value.trim(),btn=$('#btnLogin'),err=$('#loginError');
    if(!username||!password){err.textContent='Informe usuário e senha.';return}
    if(password.length<8){err.textContent='A senha deve ter pelo menos 8 caracteres.';return}
    if(setupMode&&name.length<3){err.textContent='Informe seu nome.';return}
    btn.disabled=true;btn.textContent=setupMode?'Criando…':'Entrando…';err.textContent='';
    try{
      let r;
      if(setupMode){
        if(!BOOTSTRAP_KEY||BOOTSTRAP_KEY==='__AUDITAR_SYNC_KEY__')throw new Error('A versão do Painel Mestre não recebeu a chave da Central Online.');
        r=await api('auth_bootstrap_admin',{syncKey:BOOTSTRAP_KEY,name,username,email:`${username}@auditar.local`,password,deviceId:deviceId(),platform:'windows'});
      }else{
        r=await api('auth_login',{username,email:username,password,deviceId:deviceId(),platform:'windows'});
      }
      if(!r?.ok)throw new Error(r?.message||'Usuário ou senha inválidos.');
      if(String(r.user?.role||'').toLowerCase()!=='admin')throw new Error('Este Painel Mestre é exclusivo para administradores.');
      saveSession(r);hideLogin();await refresh();
    }catch(e){err.textContent=e.message||'Não foi possível entrar.'}
    finally{btn.disabled=false;btn.textContent=setupMode?'Criar meu acesso':'Entrar'}
  }

  async function verifySavedSession(){if(!token())return false;try{const r=await api('auth_session',{authToken:token(),deviceId:deviceId(),platform:'windows'});if(!r?.ok||String(r.user?.role||'').toLowerCase()!=='admin')return false;currentUser=r.user;localStorage.setItem(USER_KEY,JSON.stringify(r.user||{}));$('#adminDisplay').textContent=r.user?.name||'Administrador';return true}catch(_){return false}}
  async function loadUsers(){const r=await api('auth_users_list');if(!r?.ok){if(['SESSION_INVALID','AUTH_REQUIRED'].includes(r?.code)){clearSession();showLogin(r.message||'Sessão expirada.');return false}throw new Error(r?.message||'Falha ao carregar usuários.')}users=Array.isArray(r.users)?r.users:[];return true}
  async function loadCompanies(){const map=new Map();let sinceVersion=0;for(let p=0;p<20;p++){const r=await api('device_sync_pull',{authToken:token(),deviceId:deviceId(),platform:'windows',sinceVersion,limit:300});if(!r?.ok)throw new Error(r?.message||'Falha ao carregar empresas.');for(const ch of (r.changes||[])){const table=String(ch.table||ch.tableName||ch.table_name||'');if(table!=='companies')continue;const id=String(ch.id||ch.recordId||ch.record_id||'').trim();if(!id)continue;if(ch.deleted===true)map.delete(id);else if(ch.payload&&typeof ch.payload==='object')map.set(id,{id,...ch.payload})}const n=Number(r.nextVersion||r.serverVersion||r.version||sinceVersion);if(n>sinceVersion)sinceVersion=n;if(r.hasMore!==true)break}companies=[...map.values()].sort((a,b)=>String(a.name||a.legal_name||'').localeCompare(String(b.name||b.legal_name||''),'pt-BR'))}
  async function refresh(){const b=$('#btnRefresh');b.disabled=true;b.textContent='↻ Atualizando…';try{if(!await loadUsers())return;try{await loadCompanies()}catch(e){companies=[];console.warn(e);toast('Usuários carregados. Empresas aguardando sincronização.')}renderAll()}catch(e){toast(e.message||'Falha ao atualizar.')}finally{b.disabled=false;b.textContent='↻ Atualizar'}}

  function openView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));const t={dashboard:['Visão geral','Controle central dos acessos do Auditar SST.'],users:['Usuários','Crie acessos, redefina senhas e controle permissões.'],companies:['Empresas','Empresas disponíveis para liberação aos técnicos.']}[id]||['Visão geral',''];$('#viewTitle').textContent=t[0];$('#viewSub').textContent=t[1];$('#btnNewUserTop').classList.toggle('hidden',id==='companies')}
  function renderAll(){renderDashboard();renderUsers();renderCompanies()}
  function renderDashboard(){const techs=users.filter(u=>String(u.role||'').toLowerCase()!=='admin');$('#mUsers').textContent=users.length;$('#mActive').textContent=users.filter(u=>u.active!==false).length;$('#mTechs').textContent=techs.length;$('#mBlocked').textContent=users.filter(u=>u.active===false).length;const restricted=techs.filter(u=>!u.allCompanies&&(u.companyIds||[]).length).length;$('#accessSummary').innerHTML=`<div class="list-item"><div><b>${companies.length} empresa(s)</b><small>Disponíveis para permissões.</small></div><span class="badge active">Central</span></div><div class="list-item"><div><b>${restricted} técnico(s) restritos</b><small>Acesso somente às empresas selecionadas.</small></div><span class="badge tech">Controlado</span></div>`;const r=users.slice().reverse().slice(0,6);$('#recentUsers').innerHTML=r.length?r.map(u=>`<div class="list-item"><div><b>${esc(u.name)}</b><small>@${esc(usernameOf(u))} • ${String(u.role).toLowerCase()==='admin'?'Administrador':'Técnico SST'}</small></div><span class="badge ${u.active===false?'inactive':'active'}">${u.active===false?'Bloqueado':'Ativo'}</span></div>`).join(''):'<div class="empty">Nenhum usuário cadastrado.</div>'}
  function accessLabel(u){if(String(u.role).toLowerCase()==='admin'||u.allCompanies)return'Todas as empresas';const n=(u.companyIds||[]).length;return n?`${n} empresa(s)`:'Nenhuma empresa'}
  function filteredUsers(){const q=$('#userSearch').value.trim().toLowerCase(),f=$('#userFilter').value;return users.filter(u=>{const role=String(u.role||'tecnico').toLowerCase();if(f==='active'&&u.active===false)return false;if(f==='inactive'&&u.active!==false)return false;if(f==='admin'&&role!=='admin')return false;if(f==='tecnico'&&role==='admin')return false;return !q||[u.name,usernameOf(u),role].some(v=>String(v||'').toLowerCase().includes(q))}).sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'pt-BR'))}
  function renderUsers(){const rows=filteredUsers();$('#usersTable').innerHTML=rows.length?`<table class="data-table"><thead><tr><th>Usuário</th><th>Perfil</th><th>Empresas</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(u=>{const admin=String(u.role).toLowerCase()==='admin',self=String(u.id)===String(currentUser?.id||'');return`<tr><td><b>${esc(u.name)}</b><br><small>@${esc(usernameOf(u))}${self?' • você':''}</small></td><td><span class="badge ${admin?'admin':'tech'}">${admin?'Administrador':'Técnico SST'}</span></td><td>${esc(accessLabel(u))}</td><td><span class="badge ${u.active===false?'inactive':'active'}">${u.active===false?'Bloqueado':'Ativo'}</span></td><td><div class="row-actions"><button class="soft" data-edit-user="${esc(u.id)}">Gerenciar</button></div></td></tr>`}).join('')}</tbody></table>`:'<div class="empty">Nenhum usuário encontrado.</div>';$$('[data-edit-user]').forEach(b=>b.onclick=()=>openUserDialog(users.find(u=>String(u.id)===String(b.dataset.editUser))))}
  function renderCompanies(){const q=$('#companySearch').value.trim().toLowerCase(),rows=companies.filter(c=>!q||[c.name,c.legal_name,c.cnpj].some(v=>String(v||'').toLowerCase().includes(q)));$('#companiesTable').innerHTML=rows.length?`<table class="data-table"><thead><tr><th>Empresa</th><th>CNPJ</th><th>Técnicos liberados</th></tr></thead><tbody>${rows.map(c=>{const n=users.filter(u=>String(u.role).toLowerCase()!=='admin'&&u.active!==false&&(u.allCompanies||(u.companyIds||[]).includes(c.id))).length;return`<tr><td><b>${esc(c.name||c.legal_name||'Empresa')}</b></td><td>${esc(c.cnpj||'—')}</td><td>${n} técnico(s)</td></tr>`}).join('')}</tbody></table>`:'<div class="empty">Nenhuma empresa sincronizada ainda.</div>'}

  function genPass(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#%';const a=new Uint32Array(12);crypto.getRandomValues(a);return[...a].map(v=>chars[v%chars.length]).join('')}
  function openUserDialog(u=null){$('#userForm').reset();$('#uId').value=u?.id||'';$('#uEmailExisting').value=u?.email||'';$('#uName').value=u?.name||'';$('#uUsername').value=u?usernameOf(u):'';$('#uUsername').disabled=!!u;$('#uRole').value=String(u?.role||'tecnico').toLowerCase()==='admin'?'admin':'tecnico';$('#uActive').checked=u?.active!==false;$('#uAllCompanies').checked=u?.allCompanies===true||String(u?.role||'').toLowerCase()==='admin';$('#uPassword').value=u?'':genPass();$('#passwordHint').textContent=u?'(opcional para redefinir)':'inicial';$('#userDialogTitle').textContent=u?'Gerenciar usuário':'Novo usuário';$('#userDialogSub').textContent=u?'Altere acesso, empresas ou defina uma nova senha.':'Crie um acesso individual para o Auditar SST.';$('#userFormError').textContent='';renderCompanyPicker(new Set(u?.companyIds||[]));syncRoleUi();const self=u&&String(u.id)===String(currentUser?.id||'');$('#uActive').disabled=!!self;$('#uRole').disabled=!!self;$('#userDialog').showModal()}
  function renderCompanyPicker(selected=null){const cur=selected||new Set($$('[data-company-check]:checked').map(x=>x.value)),q=$('#companyPickerSearch').value.trim().toLowerCase(),rows=companies.filter(c=>!q||String(c.name||c.legal_name||'').toLowerCase().includes(q));$('#companyPicker').innerHTML=rows.length?rows.map(c=>`<label class="company-check"><input data-company-check type="checkbox" value="${esc(c.id)}" ${cur.has(c.id)?'checked':''}><span><b>${esc(c.name||c.legal_name||'Empresa')}</b>${c.cnpj?`<small class="company-meta">${esc(c.cnpj)}</small>`:''}</span></label>`).join(''):'<div class="empty">Nenhuma empresa disponível.</div>'}
  function syncRoleUi(){const admin=$('#uRole').value==='admin';if(admin)$('#uAllCompanies').checked=true;$('#companyAccessWrap').classList.toggle('hidden',admin);$('#companyPickerWrap').classList.toggle('hidden',$('#uAllCompanies').checked||admin)}
  async function saveUser(){const id=$('#uId').value.trim(),name=$('#uName').value.trim(),username=cleanUsername($('#uUsername').value),role=$('#uRole').value==='admin'?'admin':'tecnico',active=$('#uActive').checked,allCompanies=role==='admin'?true:$('#uAllCompanies').checked,companyIds=role==='admin'||allCompanies?[]:$$('[data-company-check]:checked').map(x=>x.value),password=$('#uPassword').value,err=$('#userFormError');if(name.length<3){err.textContent='Informe o nome do usuário.';return}if(!id&&username.length<3){err.textContent='Crie um usuário com pelo menos 3 caracteres.';return}if(!id&&password.length<8){err.textContent='A senha inicial deve ter pelo menos 8 caracteres.';return}if(id&&password&&password.length<8){err.textContent='A nova senha deve ter pelo menos 8 caracteres.';return}const email=id?$('#uEmailExisting').value:`${username}@auditar.local`,b=$('#btnSaveUser');b.disabled=true;b.textContent='Salvando…';err.textContent='';try{const r=await api('auth_user_save',{user:{id,name,username,email,role,active,allCompanies,companyIds,...(password?{password}:{})}});if(!r?.ok)throw new Error(r?.message||'Não foi possível salvar o usuário.');$('#userDialog').close();await loadUsers();renderAll();toast(id?'Usuário atualizado.':'Usuário criado.');if(!id||password)showCredentials(usernameOf(r.user||{email}),password)}catch(e){err.textContent=e.message||'Falha ao salvar usuário.'}finally{b.disabled=false;b.textContent='Salvar usuário'}}
  function showCredentials(u,p){$('#createdUsername').textContent=u;$('#createdPassword').textContent=p||'(senha mantida)';$('#credentialDialog').showModal()}
  async function copyCredentials(){const text=`Auditar SST\nUsuário: ${$('#createdUsername').textContent}\nSenha: ${$('#createdPassword').textContent}`;try{await navigator.clipboard.writeText(text);toast('Usuário e senha copiados.')}catch(_){toast('Não foi possível copiar automaticamente.')}}

  async function init(){
    $('#btnLogin').onclick=login;$('#loginPass').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$$('.nav').forEach(n=>n.onclick=()=>openView(n.dataset.view));$('#btnRefresh').onclick=refresh;$('#btnNewUser').onclick=()=>openUserDialog();$('#btnNewUserTop').onclick=()=>openUserDialog();$('#btnSaveUser').onclick=saveUser;$('#btnGeneratePass').onclick=()=>{$('#uPassword').value=genPass();$('#uPassword').select()};$('#btnCopyCredentials').onclick=copyCredentials;$('#btnLogout').onclick=async()=>{try{if(token())await api('auth_logout')}catch(_){}clearSession();showLogin('Você saiu do Painel Mestre.')};$('#userSearch').oninput=renderUsers;$('#userFilter').onchange=renderUsers;$('#companySearch').oninput=renderCompanies;$('#companyPickerSearch').oninput=()=>renderCompanyPicker();$('#uRole').onchange=syncRoleUi;$('#uAllCompanies').onchange=syncRoleUi;$('#loginUser').oninput=e=>{const v=cleanUsername(e.target.value);if(v!==e.target.value)e.target.value=v};$('#uUsername').oninput=e=>{const v=cleanUsername(e.target.value);if(v!==e.target.value)e.target.value=v};
    try{const s=await api('auth_status');if(!s?.ok)throw new Error(s?.message||'Central indisponível.');if(s.configured===false){showLogin('A Central Online ainda não foi configurada.');return}if(s.hasUsers!==true){clearSession();showLogin('',true);return}const ok=await verifySavedSession();if(!ok){clearSession();showLogin();return}hideLogin();await refresh()}catch(e){clearSession();showLogin(e.message||'Não foi possível acessar a Central Online.')}
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();