const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
let rows = [['company_id','group_name','company_type','unit_alias','revision','updated_at','updated_by']];
const sheet = {getDataRange:()=>({getValues:()=>rows.map(r=>[...r])}), appendRow:r=>rows.push(r), getRange:()=>({setValues:v=>{rows=[rows[0],...v.map(r=>[...r])];}})};
const users = {admin:{id:'adm',role:'admin'}, tech:{id:'t',role:'tecnico'}, client:{id:'c',role:'cliente'}};
const ctx = {Number, Object, Array, String, Date, Error, LockService:{getScriptLock:()=>({waitLock:()=>{},releaseLock:()=>{}})}, ensureAuthStorage_:()=>({getSheetByName:()=>sheet}), authorizeMultiUserToken_:r=>users[r.authToken]?{ok:true,user:users[r.authToken]}:{ok:false,code:'AUTH_REQUIRED'}, userCanAccessCompany_:(u,id)=>u.role==='admin'||(u.role==='tecnico'&&id==='one')};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('feature_sources/CompanyGroupsSync_v1.gs','utf8'),ctx);
const call = request => JSON.parse(JSON.stringify(ctx.companyGroupsSync_(request)));
assert.equal(call({__authUser:users.admin}).ok,false);
assert.equal(call({authToken:'client'}).ok,false);
const change = {companyId:'one',group:'Construtora Quality',type:'Obra',alias:'Quality — Centro',baseVersion:0};
assert.equal(call({authToken:'tech',changes:[change]}).items[0].version,1);
assert.throws(()=>call({authToken:'tech',changes:[{...change,companyId:'two'}]}));
call({authToken:'admin',changes:[{...change,companyId:'two',group:'Grupo Ideal',type:'Padaria'}]});
assert.equal(call({authToken:'tech'}).items.length,1);
const previous = JSON.stringify(rows);
assert.equal(call({authToken:'admin',changes:[{...change,companyId:'two',baseVersion:1,group:'Alterado'},{...change,baseVersion:0}]}).code,'GROUP_CONFLICT');
assert.equal(JSON.stringify(rows),previous);
assert.equal(call({authToken:'tech',changes:[{...change,group:'',type:'Obra',baseVersion:1}]}).items[0].group,'');
assert.throws(()=>call({authToken:'admin',changes:[{...change,baseVersion:2},{...change,baseVersion:2}]}));
console.log('GROUPS_AUTH_ISOLATION_CAS_ATOMIC_BATCH_OFFLINE_UNLINK_OK');
